# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/mobile_notification_service/v26/mobile_notification_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/mobile_notification_service/v26/mobile_notification_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import types_pb2 as api_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEapi/mobile_notification_service/v26/mobile_notification_service.proto\x12\x0f\x61pi.gravity.v26\x1a\x16\x61pi/common/types.proto\"\xef\x01\n\x1dSendMobileNotificationRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\x46\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x38.api.gravity.v26.SendMobileNotificationRequest.DataEntry\x12\x14\n\x0c\x63ollapse_key\x18\x05 \x01(\t\x12\x13\n\x0bttl_seconds\x18\x06 \x01(\x05\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"k\n\x1eSendMobileNotificationResponse\x12\x0c\n\x04sent\x18\x01 \x01(\x05\x12\x0e\n\x06\x66\x61iled\x18\x02 \x01(\x05\x12+\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x1c.api.gravity.types.ErrorInfo\"$\n\x11SetEnabledRequest\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x32\xa5\x02\n\x19MobileNotificationService\x12g\n\x04Send\x12..api.gravity.v26.SendMobileNotificationRequest\x1a/.api.gravity.v26.SendMobileNotificationResponse\x12T\n\nSetEnabled\x12\".api.gravity.v26.SetEnabledRequest\x1a\".api.gravity.types.BooleanResponse\x12I\n\tIsEnabled\x12\x18.api.gravity.types.Empty\x1a\".api.gravity.types.BooleanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.mobile_notification_service.v26.mobile_notification_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMOBILENOTIFICATIONREQUEST_DATAENTRY']._loaded_options = None
  _globals['_SENDMOBILENOTIFICATIONREQUEST_DATAENTRY']._serialized_options = b'8\001'
  _globals['_SENDMOBILENOTIFICATIONREQUEST']._serialized_start=115
  _globals['_SENDMOBILENOTIFICATIONREQUEST']._serialized_end=354
  _globals['_SENDMOBILENOTIFICATIONREQUEST_DATAENTRY']._serialized_start=311
  _globals['_SENDMOBILENOTIFICATIONREQUEST_DATAENTRY']._serialized_end=354
  _globals['_SENDMOBILENOTIFICATIONRESPONSE']._serialized_start=356
  _globals['_SENDMOBILENOTIFICATIONRESPONSE']._serialized_end=463
  _globals['_SETENABLEDREQUEST']._serialized_start=465
  _globals['_SETENABLEDREQUEST']._serialized_end=501
  _globals['_MOBILENOTIFICATIONSERVICE']._serialized_start=504
  _globals['_MOBILENOTIFICATIONSERVICE']._serialized_end=797
# @@protoc_insertion_point(module_scope)
