"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from api.mobile_notification_service.v26 import mobile_notification_service_pb2 as _mobile_notification_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class MobileNotificationServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> MobileNotificationServiceAsyncStub: ...
    Send: _grpc.UnaryUnaryMultiCallable[_mobile_notification_service_pb2.SendMobileNotificationRequest, _mobile_notification_service_pb2.SendMobileNotificationResponse]
    """Send a push notification to all mobile devices registered by the
    authenticated user of this device.
    """
    SetEnabled: _grpc.UnaryUnaryMultiCallable[_mobile_notification_service_pb2.SetEnabledRequest, _types_pb2.BooleanResponse]
    """SetEnabled turns push notifications on/off for the whole device — a
    single RPC (not a pair) so a grant covers exactly the toggle
    capability, nothing more (e.g. not Send). Persisted across restarts
    (system_config). When disabled, Send fails immediately without
    contacting the delegate (Settings)/notif backend.
    """
    IsEnabled: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]
    """IsEnabled reports the current state set by SetEnabled."""

@_typing.type_check_only
class MobileNotificationServiceAsyncStub(MobileNotificationServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Send: _aio.UnaryUnaryMultiCallable[_mobile_notification_service_pb2.SendMobileNotificationRequest, _mobile_notification_service_pb2.SendMobileNotificationResponse]  # type: ignore[assignment]
    """Send a push notification to all mobile devices registered by the
    authenticated user of this device.
    """
    SetEnabled: _aio.UnaryUnaryMultiCallable[_mobile_notification_service_pb2.SetEnabledRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """SetEnabled turns push notifications on/off for the whole device — a
    single RPC (not a pair) so a grant covers exactly the toggle
    capability, nothing more (e.g. not Send). Persisted across restarts
    (system_config). When disabled, Send fails immediately without
    contacting the delegate (Settings)/notif backend.
    """
    IsEnabled: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """IsEnabled reports the current state set by SetEnabled."""

class MobileNotificationServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Send(
        self,
        request: _mobile_notification_service_pb2.SendMobileNotificationRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_mobile_notification_service_pb2.SendMobileNotificationResponse, _abc.Awaitable[_mobile_notification_service_pb2.SendMobileNotificationResponse]]:
        """Send a push notification to all mobile devices registered by the
        authenticated user of this device.
        """

    @_abc_1.abstractmethod
    def SetEnabled(
        self,
        request: _mobile_notification_service_pb2.SetEnabledRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """SetEnabled turns push notifications on/off for the whole device — a
        single RPC (not a pair) so a grant covers exactly the toggle
        capability, nothing more (e.g. not Send). Persisted across restarts
        (system_config). When disabled, Send fails immediately without
        contacting the delegate (Settings)/notif backend.
        """

    @_abc_1.abstractmethod
    def IsEnabled(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """IsEnabled reports the current state set by SetEnabled."""

def add_MobileNotificationServiceServicer_to_server(servicer: MobileNotificationServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
