# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.common import types_pb2 as api_dot_common_dot_types__pb2
from api.mobile_notification_service.v26 import mobile_notification_service_pb2 as api_dot_mobile__notification__service_dot_v26_dot_mobile__notification__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/mobile_notification_service/v26/mobile_notification_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MobileNotificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/api.gravity.v26.MobileNotificationService/Send',
                request_serializer=api_dot_mobile__notification__service_dot_v26_dot_mobile__notification__service__pb2.SendMobileNotificationRequest.SerializeToString,
                response_deserializer=api_dot_mobile__notification__service_dot_v26_dot_mobile__notification__service__pb2.SendMobileNotificationResponse.FromString,
                _registered_method=True)
        self.SetEnabled = channel.unary_unary(
                '/api.gravity.v26.MobileNotificationService/SetEnabled',
                request_serializer=api_dot_mobile__notification__service_dot_v26_dot_mobile__notification__service__pb2.SetEnabledRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.IsEnabled = channel.unary_unary(
                '/api.gravity.v26.MobileNotificationService/IsEnabled',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)


class MobileNotificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Send(self, request, context):
        """Send a push notification to all mobile devices registered by the
        authenticated user of this device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEnabled(self, request, context):
        """SetEnabled turns push notifications on/off for the whole device — a
        single RPC (not a pair) so a grant covers exactly the toggle
        capability, nothing more (e.g. not Send). Persisted across restarts
        (system_config). When disabled, Send fails immediately without
        contacting the delegate (Settings)/notif backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsEnabled(self, request, context):
        """IsEnabled reports the current state set by SetEnabled.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobileNotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=api_dot_mobile__notification__service_dot_v26_dot_mobile__notification__service__pb2.SendMobileNotificationRequest.FromString,
                    response_serializer=api_dot_mobile__notification__service_dot_v26_dot_mobile__notification__service__pb2.SendMobileNotificationResponse.SerializeToString,
            ),
            'SetEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEnabled,
                    request_deserializer=api_dot_mobile__notification__service_dot_v26_dot_mobile__notification__service__pb2.SetEnabledRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'IsEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.IsEnabled,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.gravity.v26.MobileNotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.gravity.v26.MobileNotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MobileNotificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.MobileNotificationService/Send',
            api_dot_mobile__notification__service_dot_v26_dot_mobile__notification__service__pb2.SendMobileNotificationRequest.SerializeToString,
            api_dot_mobile__notification__service_dot_v26_dot_mobile__notification__service__pb2.SendMobileNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.MobileNotificationService/SetEnabled',
            api_dot_mobile__notification__service_dot_v26_dot_mobile__notification__service__pb2.SetEnabledRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.MobileNotificationService/IsEnabled',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
