"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SendMobileNotificationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TITLE_FIELD_NUMBER: _builtins.int
    BODY_FIELD_NUMBER: _builtins.int
    IMAGE_URL_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    COLLAPSE_KEY_FIELD_NUMBER: _builtins.int
    TTL_SECONDS_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """Always overwritten by the runtime as "<device name> · <caller app name>",
    resolved from the caller's identity (never from what the caller sends) —
    one app can never spoof another's identity in a notification the user
    sees. Any value set here by the caller is discarded. The Go SDK doesn't
    even expose this as a parameter of MobileNotificationManager.Send.
    """
    body: _builtins.str
    image_url: _builtins.str
    collapse_key: _builtins.str
    ttl_seconds: _builtins.int
    @_builtins.property
    def data(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        body: _builtins.str = ...,
        image_url: _builtins.str = ...,
        data: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        collapse_key: _builtins.str = ...,
        ttl_seconds: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["body", b"body", "collapse_key", b"collapse_key", "data", b"data", "image_url", b"image_url", "title", b"title", "ttl_seconds", b"ttl_seconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SendMobileNotificationRequest: _TypeAlias = SendMobileNotificationRequest  # noqa: Y015

@_typing.final
class SendMobileNotificationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SENT_FIELD_NUMBER: _builtins.int
    FAILED_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    sent: _builtins.int
    failed: _builtins.int
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        sent: _builtins.int = ...,
        failed: _builtins.int = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "failed", b"failed", "sent", b"sent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SendMobileNotificationResponse: _TypeAlias = SendMobileNotificationResponse  # noqa: Y015

@_typing.final
class SetEnabledRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetEnabledRequest: _TypeAlias = SetEnabledRequest  # noqa: Y015
